const products = [
      //----Group 1----// 
    { id: 1, name: "NikNaks Original Cheese Flavoured Maize Snack 135g", price: "15.99", image: "products/shop/group1/product1/1.jpg", description: "Enjoy your childhood favourite while sharing this pack with your family. Boasting a delicious crunch and mouth-watering cheese flavour, this snack is flavoured to perfection and sure to impress your family.", additionalImages: ["products/shop/group1/product1/1.jpg", "products/shop/group1/product1/1.jpg", "products/shop/group1/product1/1.jpg"], brand: "Simba", status: "Available", category: "snack" },
    { id: 2, name: "Weet-Bix Wholegrain Wheat Biscuits 900g", price: "54.99", image: "products/shop/group1/product2/1.jpg", description: "Weet-Bix is South Africa’s number 1 selling breakfast cereal and has been part of the South African breakfast table for generations.", additionalImages: ["products/shop/group1/product2/1.jpg", "products/shop/group1/product2/2.jpg", "products/shop/group1/product2/1.jpg"], brand: "Bokomo", status: "Available", category: "breakfast" },
    { id: 3, name: "King Foods Fine Mabela Meal 1kg", price: "29.99", image: "products/shop/group1/product3/1.jpg", description: "Begin your day with King Korn Mabele Meal. It is made from 100% pure natural sorghum and is ideal as part of a healthy eating plan.", additionalImages: ["products/shop/group1/product3/1.jpg", "products/shop/group1/product3/1.jpg", "products/shop/group1/product3/1.jpg"], brand: "King Korn", status: "Available", category: "cupboard" },


    { id: 5, name: "Maggi Chicken 2 Minute Noodles 68g x 5", price: "42.99", image: "products/shop/group1/product5/1.jpg", description: "Whether your family enjoys them after school, at work or at home, Maggi 2-Minute Noodles are delicious and easy to make.", additionalImages: ["products/shop/group1/product5/1.jpg", "products/shop/group1/product5/1.jpg", "products/shop/group1/product5/1.jpg"], brand: "Maggi", status: "Available", category: "cupboard" },
    { id: 6, name: "Tastic Rice 5kg", price: "129.99", image: "products/shop/group1/product6/1.jpg", description: "Tastic Long Grain Parboiled Rice cooks up fluffy and white every time.", additionalImages: ["products/shop/group1/product6/1.jpg", "products/shop/group1/product6/1.jpg", "products/shop/group1/product6/1.jpg"], brand: "Tastic", status: "Available", category: "cupboard" },
    { id: 7, name: "Baby Soft 2Ply Fresh White Toilet Paper 24 Pack", price: "204.99", image: "products/shop/group1/product7/1.jpg", description: "Baby Soft's SoftWave technology provides the perfect balance of softness and strength to leave you and your family feeling clean, fresh and confident.", additionalImages: ["products/shop/group1/product7/1.jpg", "products/shop/group1/product7/1.jpg", "products/shop/group1/product7/1.jpg"], brand: "Baby Soft", status: "Available", category: "household&cleaning" },


    { id: 9, name: "Iwisa No. 1 Maize Rice 1kg", price: "29.99", image: "products/shop/group1/product9/1.jpg", description: "This maize rice is naturally high in energy and offers a delicious taste that complements various dishes. Carefully selected grains ensure consistency and flavour, making them perfect for traditional and modern recipes.", additionalImages: ["products/shop/group1/product9/1.jpg", "products/shop/group1/product9/1.jpg", "products/shop/group1/product9/1.jpg"], brand: "Iwisa", status: "Available", category: "cupboard" },
    { id: 10, name: "Heineken Silver Beer Bottles 6 x 330ml", price: "109.99", image: "products/shop/group1/product10/1.jpg", description: "Allow yourself to indulge in the ultimate beer-tasting experience with each invigorating sip of this extra-refreshing silver beer.", additionalImages: ["products/shop/group1/product10/1.jpg", "products/shop/group1/product10/1.jpg", "products/shop/group1/product10/1.jpg"], brand: "Heineken", status: "Available", category: "liquor" },
    { id: 11, name: "Knorr Mild Breyani Rice Mate 275g", price: "37.99", image: "products/shop/group1/product11/1.jpg", description: "Use this easy-to-prepare meal solution to take the effort out of creating delicious weekday dinners. You can prepare a scrumptious South African classic without spending hours in the kitchen.", additionalImages: ["products/shop/group1/product11/1.jpg", "products/shop/group1/product11/1.jpg", "products/shop/group1/product11/1.jpg"], brand: "knorr", status: "Available", category: "spices&soup"},
  
];